sims/humans/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, InputRequired, NumberRange, Regexp

from sims.models import Gender


class HumanForm(FlaskForm):
    name = StringField('Name',
                       validators=[DataRequired(), Regexp(r'^[A-Za-z]+$', message='Name should contain only letters.')])
    surname = StringField('Surname', validators=[DataRequired(), Regexp(r'^[A-Za-z]+$',
                                                                        message='Surname should contain only letters.')])
    gender = SelectField('Gender', choices=[(gender.value, gender.value) for gender in Gender],
                         validators=[DataRequired()])
    age = IntegerField('Age', validators=[InputRequired(), NumberRange(min=0, max=100)])
    job = SelectField('Job', coerce=int, default=None)
    x_coordinate = IntegerField('X coordinate', validators=[DataRequired(), NumberRange(min=-450, max=450)])
    y_coordinate = IntegerField('Y coordinate', validators=[DataRequired(), NumberRange(min=-200, max=200)])
    submit = SubmitField('Done')


class HumanJobForm(FlaskForm):
    job = SelectField('Job', coerce=int)
    submit = SubmitField('Done')


class HumanCoordinatesForm(FlaskForm):
    x_coordinate = IntegerField('X coordinate', validators=[DataRequired(), NumberRange(min=-450, max=450)])
    y_coordinate = IntegerField('Y coordinate', validators=[DataRequired(), NumberRange(min=-200, max=200)])
    submit = SubmitField('Done')

sims/families/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.families.forms import FamilyForm
from sims.models import Human, Family, Pet, Jobs
from flask_login import login_required

families = Blueprint('families', __name__)


@families.route("/family/new", methods=['GET', 'POST'])
@login_required
def new_family():
    form = FamilyForm()

    if form.validate_on_submit():
        family = Family(name=form.name.data)

        db.session.add(family)
        db.session.commit()

        flash('Family has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('families/create_family.html', title='New Family',
                           form=form, legend='New Family')


def get_family_money(humans_in_family):
    print(humans_in_family)
    total = 0
    for human in humans_in_family:
        job = Jobs.query.get(human.job_id)
        total += job.salary
    return total

@families.route("/family/<int:family_id>")
def family(family_id):
    family = Family.query.get_or_404(family_id)
    humans_in_family = Human.query.filter_by(family_id=family.id).all()
    pets_in_family = Pet.query.filter_by(family_id=family.id).all()

    return render_template('families/family.html', family=family,
                           humans_in_family=humans_in_family,
                           pets_in_family=pets_in_family,
                           total_money=get_family_money(humans_in_family))


@families.route("/family/<int:family_id>/update", methods=['GET', 'POST'])
@login_required
def update_family(family_id):
    family = Family.query.get_or_404(family_id)

    form = FamilyForm()
    if form.validate_on_submit():
        family.name = form.name.data
        db.session.commit()
        flash('Your family has been updated!', 'success')
        return redirect(url_for('families.family', family_id=family.id))
    elif request.method == 'GET':
        form.name.data = family.name

    return render_template('families/create_family.html', form=form, legend='Update Family', title='Update Family')


@families.route("/family/<int:family_id>/delete", methods=['POST'])
@login_required
def delete_family(family_id):
    family = Family.query.get_or_404(family_id)

    Pet.query.filter_by(family_id=family.id).update({Pet.family_id: None})
    Human.query.filter_by(family_id=family.id).update({Human.family_id: None})

    db.session.delete(family)
    db.session.commit()
    flash('Family has been deleted!', 'success')
    return redirect(url_for('main.home'))


@families.route("/families")
@login_required
def all_families():
    families = Family.query.all()
    return render_template('families/families.html', title='List of Families',
                           families=families)


@families.route("/families/human/<int:human_id>", methods=['GET', 'POST'])
@login_required
def families_human(human_id):
    families = Family.query.all()
    return render_template('families/families_human.html', title='List of Families',
                           families=families, human_id=human_id)


@families.route("/families/pet/<int:pet_id>", methods=['GET', 'POST'])
@login_required
def families_pet(pet_id):
    families = Family.query.all()
    return render_template('families/families_pet.html', title='List of Families',
                           families=families, pet_id=pet_id)


@families.route("/families/house/<int:house_id>", methods=['GET', 'POST'])
@login_required
def families_house(house_id):
    families = Family.query.all()
    return render_template('families/families_house.html', title='List of Families',
                           families=families, house_id=house_id)


@families.route("/family/human_join/<int:family_id>/<int:human_id>", methods=['GET', 'POST'])
@login_required
def human_join_family(family_id, human_id):
    human = Human.query.get_or_404(human_id)
    family = Family.query.get_or_404(family_id)

    if human.surname != family.name:
        flash(f'{human.name} doesn\'t have {family.name} surname.', 'danger')
        return redirect(url_for('humans.human', human_id=human.id))

    human.family_id = family_id
    db.session.commit()

    flash(f'{human.name} has joined {family.name} family!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@families.route("/family/pet_join/<int:family_id>/<int:pet_id>", methods=['GET', 'POST'])
@login_required
def pet_join_family(family_id, pet_id):
    pet = Pet.query.get_or_404(pet_id)
    family = Family.query.get_or_404(family_id)

    pet.family_id = family_id
    db.session.commit()

    flash(f'{pet.name} has joined {family.name} family!', 'success')
    return redirect(url_for('pets.pet', pet_id=pet.id))

sims/humans/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.humans.forms import HumanForm, HumanCoordinatesForm, HumanJobForm
from sims.models import Human, Family, Gender, Jobs
from flask_login import login_required

humans = Blueprint('humans', __name__)


@humans.route("/human/new", methods=['GET', 'POST'])
@login_required
def new_human():
    form = HumanForm()

    # Put all jobs from Job table to the form
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        try:
            # job = Job(form.job.data)
            gender = Gender(form.gender.data)
            job_id = int(form.job.data)
        except (KeyError, ValueError):
            flash('Invalid gender or job type', 'danger')
            return redirect(url_for('main.home'))

        human = Human(name=form.name.data, surname=form.surname.data,
                      gender=gender, age=form.age.data, job_id=job_id,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(human)
        db.session.commit()
        flash('Human has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('humans/create_human.html', title='New Human',
                           form=form, legend='New Human')


@humans.route("/human/<int:human_id>")
def human(human_id):
    human = Human.query.get_or_404(human_id)
    family = Family.query.get(human.family_id)
    job = Jobs.query.get(human.job_id)
    return render_template('humans/human.html', human=human, family=family, job=job)


@humans.route("/human/<int:human_id>/update", methods=['GET', 'POST'])
@login_required
def update_human(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]
    form.x_coordinate.data = human.x_coordinate
    form.y_coordinate.data = human.y_coordinate

    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
        except (KeyError, ValueError):
            flash('Invalid gender type', 'danger')
            return redirect(url_for('main.home'))

        human.name = form.name.data
        human.surname = form.surname.data
        human.gender = gender
        human.job_id = form.job.data
        human.age = form.age.data

        db.session.commit()
        flash('Your human has been updated!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.gender.default = human.gender.value
        form.process()

        form.name.data = human.name
        form.surname.data = human.surname
        form.age.data = human.age

    return render_template('humans/create_human.html', form=form, legend='Update Human',
                           title='Update Human', target='EDIT')


@humans.route("/human/<int:human_id>/delete", methods=['POST'])
@login_required
def delete_human(human_id):
    human = Human.query.get_or_404(human_id)

    db.session.delete(human)
    db.session.commit()
    flash('Human has been deleted!', 'success')
    return redirect(url_for('main.home'))


@humans.route("/human/<int:human_id>/leave_family", methods=['POST'])
@login_required
def human_leave_family(human_id):
    human = Human.query.get_or_404(human_id)
    human.family_id = None

    db.session.commit()
    flash(f'{human.name} left the family!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/humans/vehicle/<int:vehicle_id>", methods=['GET', 'POST'])
@login_required
def humans_vehicle(vehicle_id):
    humans = Human.query.all()
    return render_template('humans/humans_vehicle.html', title='List of Humans',
                           humans=humans, vehicle_id=vehicle_id)


@humans.route("/human/<int:human_id>/change_job", methods=['GET', 'POST'])
def change_job(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanJobForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        human.job_id = form.job.data

        db.session.commit()
        flash('Job has been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        job = Jobs.query.get(human.job_id)
        if job:
            form.job.default = job.id
            form.process()

    return render_template('humans/change_job.html', form=form, legend='Change Job',
                           title='Change Job', human=human)


@humans.route("/human/<int:human_id>/leave_job", methods=['POST'])
def leave_job(human_id):
    human = Human.query.get_or_404(human_id)
    human.job_id = None

    db.session.commit()
    flash(f'{human.name} left the job!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/human/<int:human_id>/change_coordinates", methods=['GET', 'POST'])
def change_coordinates(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanCoordinatesForm()
    if form.validate_on_submit():
        human.x_coordinate = form.x_coordinate.data
        human.y_coordinate = form.y_coordinate.data

        flash('Coordinates have been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.x_coordinate.data = human.x_coordinate
        form.y_coordinate.data = human.y_coordinate
    return render_template('humans/change_coordinates.html', form=form, legend='Change Coordinates',
                           title='Update Coordinates')

sims/vehicles/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.models import VehicleType, Color, Vehicle, Human
from flask_login import login_required

from sims.vehicles.forms import VehicleForm, VehicleColorForm

vehicles = Blueprint('vehicles', __name__)

ADULT_AGE = 18

@vehicles.route("/vehicle/new", methods=['GET', 'POST'])
@login_required
def new_vehicle():
    form = VehicleForm()
    if form.validate_on_submit():
        try:
            vehicle_type = VehicleType(form.type.data)
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid vehicle or color type', 'danger')
            return redirect(url_for('main.home'))
        vehicle = Vehicle(plate=form.plate.data, type=vehicle_type, color=color,
                          x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(vehicle)
        db.session.commit()
        flash('Vehicle has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('vehicles/create_vehicle.html', title='New vehicle',
                           form=form, legend='New Vehicle')


@vehicles.route("/vehicle/<int:vehicle_id>")
def vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    human = Human.query.get(vehicle.human_id)
    return render_template('vehicles/vehicle.html', vehicle=vehicle, human=human)


@vehicles.route("/vehicle/<int:vehicle_id>/update", methods=['GET', 'POST'])
@login_required
def update_vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    form = VehicleForm()
    if form.validate_on_submit():
        try:
            vehicle_type = VehicleType(form.type.data)
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid vehicle type', 'danger')
            return redirect(url_for('main.home'))
        vehicle.plate = form.plate.data
        vehicle.type = vehicle_type
        vehicle.color = color
        vehicle.x_coordinate = form.x_coordinate.data
        vehicle.y_coordinate = form.y_coordinate.data
        db.session.commit()
        flash('Your vehicle has been updated!', 'success')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))
    elif request.method == 'GET':
        form.type.default = vehicle.type.value
        form.color.default = vehicle.color.value
        form.process()

        form.plate.data = vehicle.plate
        form.x_coordinate.data = vehicle.x_coordinate
        form.y_coordinate.data = vehicle.y_coordinate
    return render_template('vehicles/create_vehicle.html', form=form, legend='Update Vehicle', title='Update Vehicle')


@vehicles.route("/vehicle/<int:vehicle_id>/delete", methods=['POST'])
@login_required
def delete_vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    db.session.delete(vehicle)
    db.session.commit()
    flash('Vehicle has been deleted!', 'success')
    return redirect(url_for('main.home'))


def is_adult(human):
    return not human.age < ADULT_AGE


@vehicles.route("/vehicle/<int:vehicle_id>/add_human/<int:human_id>", methods=['POST', 'GET'])
@login_required
def vehicle_add_human(vehicle_id, human_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    human = Human.query.get_or_404(human_id)

    if not is_adult(human):
        flash(f'{human.name} is not adult!', 'danger')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))

    vehicle.human_id = human.id
    db.session.commit()
    flash('Owner has been added!', 'success')
    return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))


@vehicles.route("/vehicle/<int:vehicle_id>/leave_human", methods=['POST'])
@login_required
def vehicle_delete_human(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    vehicle.human_id = None

    db.session.commit()
    flash('Human has been deleted!', 'success')
    return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))


@vehicles.route("/vehicle/<int:vehicle_id>/change_color", methods=['GET', 'POST'])
def change_color(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    form = VehicleColorForm(color=2)
    if form.validate_on_submit():
        try:
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid color type', 'danger')
            return redirect(url_for('main.home'))

        vehicle.color = color
        db.session.commit()
        flash('Color has been changed!', 'success')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))
    elif request.method == 'GET':
        form.color.default = vehicle.color.value
        form.process()


    return render_template('vehicles/change_color.html', form=form, legend='Change Color', title='Update Color')

sims/templates/humans/change_coordinates.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.x_coordinate.label(class="form-control-label") }}
                    {% if form.x_coordinate.errors %}
                        {{ form.x_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.x_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.x_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.y_coordinate.label(class="form-control-label") }}
                    {% if form.y_coordinate.errors %}
                        {{ form.y_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.y_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.y_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/humans/change_job.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.job.label(class="form-control-label") }}
                    {% if form.job.errors %}
                        {{ form.job(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.job.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.job(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/humans/create_human.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.surname.label(class="form-control-label") }}
                    {% if form.surname.errors %}
                        {{ form.surname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.surname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.surname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.gender.label(class="form-control-label") }}
                    {% if form.gender.errors %}
                        {{ form.gender(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.gender.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.gender(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.age.label(class="form-control-label") }}
                    {% if form.age.errors %}
                        {{ form.age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.age.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.job.label(class="form-control-label") }}
                    {% if form.job.errors %}
                        {{ form.job(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.job.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.job(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                {% if target != 'EDIT' %}

                    <div class="form-group">
                        {{ form.x_coordinate.label(class="form-control-label") }}
                        {% if form.x_coordinate.errors %}
                            {{ form.x_coordinate(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.x_coordinate.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.x_coordinate(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.y_coordinate.label(class="form-control-label") }}
                        {% if form.y_coordinate.errors %}
                            {{ form.y_coordinate(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.y_coordinate.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.y_coordinate(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                {% endif %}
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/humans/human.html
{% extends "layout.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-steel text-white">
                        <h2 class="text-white">{{ human.name }} {{ human.surname }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="lead">🚻 Gender: {{ human.gender.value }}</p>
                        <p class="lead">🕛 Age: {{ human.age }}</p>
                        {% if job %}
                            <p class="lead">💼 Job: {{ job.name }}</p>
                            <p class="lead">💰 Salary: {{ job.salary }}</p>
                        {% else %}
                            <p class="lead">💼 Job: Unemployed</p>
                        {% endif %}
                        <p class="lead">📍 Coordinates: ({{ human.x_coordinate }}, {{ human.y_coordinate }})</p>
                        {% if family %}
                            <p class="lead">👨‍👨‍👧 Family: {{ family.name }}</p>
                        {% else %}
                            <p class="lead">👨‍👨‍👧 Family: Not in the family</p>
                        {% endif %}
                        <p class="lead">🔹 Plumbob: {{ human.plumbob.value }}</p>

                        <div class="mt-3">
                            <a href="{{ url_for('humans.update_human', human_id=human.id) }}" class="btn btn-primary">Edit</a>
                            <a href="{{ url_for('families.families_human', human_id=human.id) }}"
                               class="btn btn-primary">Join a Family</a>
                            <a href="{{ url_for('humans.change_job', human_id=human.id) }}"
                               class="btn btn-primary">Change Job</a>
                            <a href="{{ url_for('humans.change_coordinates', human_id=human.id) }}"
                               class="btn btn-primary">Change Coordinates</a>
                            <button class="btn btn-danger" id="deleteBtn" data-toggle="modal"
                                    data-target="#deleteModal">Delete
                            </button>
                            {% if family %}
                                <form class="mt-3"
                                      action="{{ url_for('humans.human_leave_family', human_id=human.id) }}"
                                      method="POST">
                                    <input class="btn btn-primary" type="submit" value="Leave the Family">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Human?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('humans.delete_human', human_id=human.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

sims/templates/humans/humans_vehicle.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h1>List of Humans</h1>
        <ul class="list-group">
            {% for human in humans %}
                <li class="list-group-item d-flex justify-content-between align-items-center mb-3">
                    <h3 class="mb-0">{{ human.name }}</h3>
                    <a href="{{ url_for('vehicles.vehicle_add_human', vehicle_id=vehicle_id, human_id=human.id) }}" class="btn btn-outline-info">Make owner</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}