sims/houses/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.houses.forms import HouseForm
from sims.models import House, HouseType, Family
from flask_login import login_required

houses = Blueprint('houses', __name__)


@houses.route("/house/new", methods=['GET', 'POST'])
@login_required
def new_house():
    form = HouseForm()
    if form.validate_on_submit():
        try:
            house_type = HouseType(form.type.data)
        except KeyError:
            flash('Invalid house type', 'danger')
            return redirect(url_for('main.home'))
        house = House(type=house_type,
                      room_number=form.room_number.data, floor_number=form.floor_number.data,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(house)
        db.session.commit()
        flash('House has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('houses/create_house.html', title='New house',
                           form=form, legend='New House')


@houses.route("/house/<int:house_id>")
def house(house_id):
    house = House.query.get_or_404(house_id)
    family = Family.query.get(house.family_id)
    return render_template('houses/house.html', house=house, family=family)


@houses.route("/house/<int:house_id>/update", methods=['GET', 'POST'])
@login_required
def update_house(house_id):
    house = House.query.get_or_404(house_id)
    # if house.author != current_user:
    # abort(403)
    form = HouseForm()
    if form.validate_on_submit():
        try:
            house_type = HouseType(form.type.data)
        except KeyError:
            flash('Invalid house type', 'danger')
            return redirect(url_for('main.home'))
        house.type = house_type
        house.room_number = form.room_number.data
        house.floor_number = form.floor_number.data
        house.x_coordinate = form.x_coordinate.data
        house.y_coordinate = form.y_coordinate.data
        db.session.commit()
        flash('Your house has been updated!', 'success')
        return redirect(url_for('houses.house', house_id=house.id))
    elif request.method == 'GET':
        form.type.default = house.type.value
        form.process()

        form.room_number.data = house.room_number
        form.floor_number.data = house.floor_number
        form.x_coordinate.data = house.x_coordinate
        form.y_coordinate.data = house.y_coordinate

    return render_template('houses/create_house.html', form=form, legend='Update House', title='Update House')


@houses.route("/house/<int:house_id>/delete", methods=['POST'])
@login_required
def delete_house(house_id):
    house = House.query.get_or_404(house_id)

    db.session.delete(house)
    db.session.commit()
    flash('House has been deleted!', 'success')
    return redirect(url_for('main.home'))


@houses.route("/house/<int:house_id>/add_family/<int:family_id>", methods=['POST', 'GET'])
@login_required
def house_add_family(house_id, family_id):
    house = House.query.get_or_404(house_id)
    family = Family.query.get_or_404(family_id)

    house.family_id = family.id
    db.session.commit()
    flash('Family has been added!', 'success')
    return redirect(url_for('houses.house', house_id=house.id))


@houses.route("/house/<int:house_id>/leave_family", methods=['POST'])
@login_required
def house_leave_family(house_id):
    house = House.query.get_or_404(house_id)
    house.family_id = None

    db.session.commit()
    flash('Family has been deleted!', 'success')
    return redirect(url_for('houses.house', house_id=house.id))

sims/humans/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.humans.forms import HumanForm, HumanCoordinatesForm, HumanJobForm
from sims.models import Human, Family, Gender, Jobs
from flask_login import login_required

humans = Blueprint('humans', __name__)


@humans.route("/human/new", methods=['GET', 'POST'])
@login_required
def new_human():
    form = HumanForm()

    # Put all jobs from Job table to the form
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        try:
            # job = Job(form.job.data)
            gender = Gender(form.gender.data)
            job_id = int(form.job.data)
        except (KeyError, ValueError):
            flash('Invalid gender or job type', 'danger')
            return redirect(url_for('main.home'))

        human = Human(name=form.name.data, surname=form.surname.data,
                      gender=gender, age=form.age.data, job_id=job_id,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(human)
        db.session.commit()
        flash('Human has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('humans/create_human.html', title='New Human',
                           form=form, legend='New Human')


@humans.route("/human/<int:human_id>")
def human(human_id):
    human = Human.query.get_or_404(human_id)
    family = Family.query.get(human.family_id)
    job = Jobs.query.get(human.job_id)
    return render_template('humans/human.html', human=human, family=family, job=job)


@humans.route("/human/<int:human_id>/update", methods=['GET', 'POST'])
@login_required
def update_human(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]
    form.x_coordinate.data = human.x_coordinate
    form.y_coordinate.data = human.y_coordinate

    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
        except (KeyError, ValueError):
            flash('Invalid gender type', 'danger')
            return redirect(url_for('main.home'))

        human.name = form.name.data
        human.surname = form.surname.data
        human.gender = gender
        human.job_id = form.job.data
        human.age = form.age.data

        db.session.commit()
        flash('Your human has been updated!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.gender.default = human.gender.value
        form.process()

        form.name.data = human.name
        form.surname.data = human.surname
        form.age.data = human.age

    return render_template('humans/create_human.html', form=form, legend='Update Human',
                           title='Update Human', target='EDIT')


@humans.route("/human/<int:human_id>/delete", methods=['POST'])
@login_required
def delete_human(human_id):
    human = Human.query.get_or_404(human_id)

    db.session.delete(human)
    db.session.commit()
    flash('Human has been deleted!', 'success')
    return redirect(url_for('main.home'))


@humans.route("/human/<int:human_id>/leave_family", methods=['POST'])
@login_required
def human_leave_family(human_id):
    human = Human.query.get_or_404(human_id)
    human.family_id = None

    db.session.commit()
    flash(f'{human.name} left the family!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/humans/vehicle/<int:vehicle_id>", methods=['GET', 'POST'])
@login_required
def humans_vehicle(vehicle_id):
    humans = Human.query.all()
    return render_template('humans/humans_vehicle.html', title='List of Humans',
                           humans=humans, vehicle_id=vehicle_id)


@humans.route("/human/<int:human_id>/change_job", methods=['GET', 'POST'])
def change_job(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanJobForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        human.job_id = form.job.data

        db.session.commit()
        flash('Job has been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        job = Jobs.query.get(human.job_id)
        if job:
            form.job.default = job.id
            form.process()

    return render_template('humans/change_job.html', form=form, legend='Change Job',
                           title='Change Job', human=human)


@humans.route("/human/<int:human_id>/leave_job", methods=['POST'])
def leave_job(human_id):
    human = Human.query.get_or_404(human_id)
    human.job_id = None

    db.session.commit()
    flash(f'{human.name} left the job!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/human/<int:human_id>/change_coordinates", methods=['GET', 'POST'])
def change_coordinates(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanCoordinatesForm()
    if form.validate_on_submit():
        human.x_coordinate = form.x_coordinate.data
        human.y_coordinate = form.y_coordinate.data

        flash('Coordinates have been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.x_coordinate.data = human.x_coordinate
        form.y_coordinate.data = human.y_coordinate
    return render_template('humans/change_coordinates.html', form=form, legend='Change Coordinates',
                           title='Update Coordinates')

sims/jobs/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.families.forms import FamilyForm
from sims.jobs.forms import JobForm
from sims.models import Human, Family, Pet, Jobs
from flask_login import login_required

jobs = Blueprint('jobs', __name__)


@jobs.route("/job/new", methods=['GET', 'POST'])
@login_required
def new_job():
    form = JobForm()

    if form.validate_on_submit():
        job = Jobs(name=form.name.data, salary=form.salary.data)

        db.session.add(job)
        db.session.commit()

        flash('Job has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('jobs/create_job.html', title='New Job',
                           form=form, legend='New Job')


@jobs.route("/job/<int:job_id>")
def job(job_id):
    job = Jobs.query.get_or_404(job_id)

    return render_template('jobs/job.html', job=job)


@jobs.route("/job/<int:job_id>/update", methods=['GET', 'POST'])
@login_required
def update_job(job_id):
    job = Jobs.query.get_or_404(job_id)

    form = JobForm()
    if form.validate_on_submit():
        job.name = form.name.data
        job.salary = form.salary.data
        db.session.commit()
        flash('Your job has been updated!', 'success')
        return redirect(url_for('jobs.job', job_id=job.id))
    elif request.method == 'GET':
        form.name.data = job.name
        form.salary.data = job.salary

    return render_template('jobs/create_job.html', form=form, legend='Update Job', title='Update Job')


@jobs.route("/job/<int:job_id>/delete", methods=['POST'])
@login_required
def delete_job(job_id):
    job = Jobs.query.get_or_404(job_id)

    Human.query.filter_by(job_id=job.id).update({Human.job_id: None})

    db.session.delete(job)
    db.session.commit()
    flash('Job has been deleted!', 'success')
    return redirect(url_for('main.home'))


@jobs.route("/jobs")
@login_required
def all_jobs():
    jobs = Jobs.query.all()
    return render_template('jobs/jobs.html', title='List of jobs',
                           jobs=jobs)

sims/pets/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.pets.forms import PetForm
from sims.models import Pet, Family, PetType, Plumbob, Gender
from flask_login import login_required

pets = Blueprint('pets', __name__)

@pets.route("/pet/new", methods=['GET', 'POST'])
@login_required
def new_pet():
    form = PetForm()
    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
            pet_type = PetType(form.type.data)
        except KeyError:
            flash('Invalid pet or gender type', 'danger')
            return redirect(url_for('main.home'))
        pet = Pet(name=form.name.data, type=pet_type, gender=gender, age=form.age.data,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(pet)
        db.session.commit()
        flash('Pet has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('pets/create_pet.html', title='New Pet',
                           form=form, legend='New Pet')


@pets.route("/pet/<int:pet_id>")
def pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    family = Family.query.get(pet.family_id)
    return render_template('pets/pet.html', pet=pet, family=family)


@pets.route("/pet/<int:pet_id>/update", methods=['GET', 'POST'])
@login_required
def update_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)

    form = PetForm()
    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
            pet_type = PetType(form.type.data)
        except KeyError:
            flash('Invalid pet or gender type', 'danger')
            return redirect(url_for('main.home'))
        pet.name = form.name.data
        pet.type = pet_type
        pet.gender = gender
        pet.age = form.age.data
        pet.x_coordinate = form.x_coordinate.data
        pet.y_coordinate = form.y_coordinate.data
        db.session.commit()
        flash('Your pet has been updated!', 'success')
        return redirect(url_for('pets.pet', pet_id=pet.id))
    elif request.method == 'GET':
        form.gender.default = pet.gender.value
        form.type.default = pet.type.value
        form.process()

        form.name.data = pet.name
        form.age.data = pet.age
        form.x_coordinate.data = pet.x_coordinate
        form.y_coordinate.data = pet.y_coordinate
    return render_template('pets/create_pet.html', form=form, legend='Update Pet', title='Update Pet')


@pets.route("/pet/<int:pet_id>/delete", methods=['POST'])
@login_required
def delete_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)

    db.session.delete(pet)
    db.session.commit()
    flash('Pet has been deleted!', 'success')
    return redirect(url_for('main.home'))


@pets.route("/pet/<int:pet_id>/leave_family", methods=['POST'])
@login_required
def pet_leave_family(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    pet.family_id = None

    db.session.commit()
    flash(f'{pet.name} left the family!', 'success')
    return redirect(url_for('pets.pet', pet_id=pet.id))

sims/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db, bcrypt
from sims.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from sims.models import User
from flask_login import login_user, current_user, logout_user, login_required

from sims.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

sims/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="text-center border-bottom">Sims Map</h1>
    <div id="plot-container" class="border border-dark"></div>
    <script>
        const width = 1000;
        const height = 500;

        const svg = d3.select("#plot-container")
            .append("svg")
            .attr("width", width)
            .attr("height", height);

        {% for human in humans %}
            {% if human.gender.value == "Male" %}
                const human_emoji_{{ human.id }} = "🧍‍♂️"
            {% elif human.gender.value == "Female" %}
                const human_emoji_{{ human.id }} = "🧍‍♀️"
            {% else %}
                const human_emoji_{{ human.id }} = "🚁"
            {% endif %}
            svg.append("text")
                .attr("x", width / 2 + {{ human.x }})
                .attr("y", height / 2 - {{ human.y }})
                .text(human_emoji_{{ human.id }})
                .attr("fill", "black")
                .style("font-size", "20px")
                .on("click", function () {
                    const url = "{{ url_for('humans.human', human_id=human.id) }}";
                    window.location.href = url;
                });

            svg.append("text")
                .attr("x", width / 2 + {{ human.x }})
                .attr("y", height / 2 - {{ human.y }} -20)
                .text("{{ human.name }}")
                .attr("fill", "black")
                .style("font-size", "10px")
                .on("click", function () {
                    const url = "{{ url_for('humans.human', human_id=human.id) }}";
                    window.location.href = url;
                });
        {% endfor %}

        {% for pet in pets %}
            {% if pet.type.value == "Cat" %}
                const pet_emoji_{{ pet.id }} = "🐈"
            {% elif pet.type.value == "Dog" %}
                const pet_emoji_{{ pet.id }} = "🐕"
            {% elif pet.type.value == "Hamster" %}
                const pet_emoji_{{ pet.id }} = "🐹"
            {% elif pet.type.value == "Fish" %}
                const pet_emoji_{{ pet.id }} = "🐟"
            {% else %}
                const pet_emoji_{{ pet.id }} = "🦜"
            {% endif %}
            svg.append("text")
                .attr("x", width / 2 + {{ pet.x }})
                .attr("y", height / 2 - {{ pet.y }})
                .text(pet_emoji_{{ pet.id }})
                .attr("fill", "black")
                .style("font-size", "20px")
                .on("click", function () {
                    const url = "{{ url_for('pets.pet', pet_id=pet.id) }}";
                    window.location.href = url;
                });

            svg.append("text")
                .attr("x", width / 2 + {{ pet.x }} +3)
                .attr("y", height / 2 - {{ pet.y }} -20)
                .text("{{ pet.name }}")
                .attr("fill", "black")
                .style("font-size", "10px")
                .on("click", function () {
                    const url = "{{ url_for('pets.pet', pet_id=pet.id) }}";
                    window.location.href = url;
                });
        {% endfor %}

        {% for house in houses %}
            svg.append("text")
                .attr("x", width / 2 + {{ house.x }})
                .attr("y", height / 2 - {{ house.y }})
                .text("🏠︎")
                .attr("fill", "black")
                .style("font-size", "20px")
                .on("click", function () {
                    const url = "{{ url_for('houses.house', house_id=house.id) }}";
                    window.location.href = url;
                });

            svg.append("text")
                .attr("x", width / 2 + {{ house.x }} -5)
                .attr("y", height / 2 - {{ house.y }} -20)
                .text("House")
                .attr("fill", "black")
                .style("font-size", "10px")
                .on("click", function () {
                    const url = "{{ url_for('houses.house', house_id=house.id) }}";
                    window.location.href = url;
                });
        {% endfor %}

        {% for vehicle in vehicles %}
            {% if vehicle.type.value == "Car" %}
                const vehicle_emoji_{{ vehicle.id }} = "🚗"
            {% elif vehicle.type.value == "Truck" %}
                const vehicle_emoji_{{ vehicle.id }} = "🚛"
            {% elif vehicle.type.value == "Motorcycle" %}
                const vehicle_emoji_{{ vehicle.id }} = "🏍️"
            {% else %}
                const vehicle_emoji_{{ vehicle.id }} = "🚌"
            {% endif %}
            svg.append("text")
                .attr("x", width / 2 + {{ vehicle.x }})
                .attr("y", height / 2 - {{ vehicle.y }})
                .text(vehicle_emoji_{{ vehicle.id }})
                .attr("fill", "black")
                .style("font-size", "20px")
                .on("click", function () {
                    const url = "{{ url_for('vehicles.vehicle', vehicle_id=vehicle.id) }}";
                    window.location.href = url;
                });

            svg.append("text")
                .attr("x", width / 2 + {{ vehicle.x }} -5)
                .attr("y", height / 2 - {{ vehicle.y }} -20)
                .text("{{ vehicle.plate }}")
                .attr("fill", "black")
                .style("font-size", "10px")
                .on("click", function () {
                    const url = "{{ url_for('vehicles.vehicle', vehicle_id=vehicle.id) }}";
                    window.location.href = url;
                });
        {% endfor %}
    </script>
    <div class="mt-3 text-center">
        <a href="{{ url_for('humans.new_human') }}" class="btn btn-success mb-2">New Human</a>
        <a href="{{ url_for('pets.new_pet') }}" class="btn btn-success mb-2">New Pet</a>
        <a href="{{ url_for('houses.new_house') }}" class="btn btn-success mb-2">New House</a>
        <a href="{{ url_for('families.new_family') }}" class="btn btn-success mb-2">New Family</a>
        <a href="{{ url_for('vehicles.new_vehicle') }}" class="btn btn-success mb-2">New Vehicle</a>
        <a href="{{ url_for('jobs.new_job') }}" class="btn btn-success mb-2">New Job</a>
        <br>
        <a href="{{ url_for('families.all_families') }}" class="btn btn-info mb-2">All Families</a>
        <a href="{{ url_for('jobs.all_jobs') }}" class="btn btn-info mb-2">All Jobs</a>
    </div>
{% endblock content %}

sims/templates/human.html
{% extends "layout.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-steel text-white">
                        <h2 class="text-white">{{ human.name }} {{ human.surname }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="lead">Age: {{ human.age }}</p>
                        <p class="lead">Coordinates: ({{ human.x_coordinate }}, {{ human.y_coordinate }})</p>

                        <div class="mt-3">
                            <a href="{{ url_for('humans.update_human', human_id=human.id) }}" class="btn btn-primary">Edit</a>
                            <button class="btn btn-danger" id="deleteBtn" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Human?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('humans.delete_human', human_id=human.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{#    <script>#}
{#        // Add a click event listener for the delete button#}
{#        document.getElementById('deleteBtn').addEventListener('click', function () {#}
{#            if (confirm('Are you sure you want to delete this human?')) {#}
{#                const deleteUrl = "{{ url_for('delete_human', human_id=human.id) }}";#}
{#                window.location.href = deleteUrl;#}
{#            }#}
{#        });#}
{#    </script>#}
{% endblock content %}

sims/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Icon -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Sims - {{ title }}</title>
    {% else %}
        <title>Sims</title>
    {% endif %}

    <link rel="icon" type="image/jpg" href="{{ url_for('static', filename='sims-icon.jpg') }}">

    <!-- D3.js -->
    <script src="https://d3js.org/d3.v6.min.js"></script>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-info fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Sims</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="https://github.com/illds/sims">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>
</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>