sims/vehicles/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, SelectField, StringField
from wtforms.validators import DataRequired, NumberRange

from sims.models import VehicleType, Color


class VehicleForm(FlaskForm):
    plate = StringField('Plate №', validators=[DataRequired()])
    type = SelectField('Type', choices=[(vehicle_type.value, vehicle_type.value) for vehicle_type in VehicleType],
                       validators=[DataRequired()])
    color = SelectField('Color', choices=[(color.value, color.value) for color in Color],
                       validators=[DataRequired()])
    x_coordinate = IntegerField('X coordinate', validators=[DataRequired(), NumberRange(min=-450, max=450)])
    y_coordinate = IntegerField('Y coordinate', validators=[DataRequired(), NumberRange(min=-200, max=200)])
    submit = SubmitField('Done')


class VehicleColorForm(FlaskForm):
    color = SelectField('Color', choices=[(color.value, color.value) for color in Color],
                        validators=[DataRequired()])
    submit = SubmitField('Done')

sims/humans/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.humans.forms import HumanForm, HumanCoordinatesForm, HumanJobForm
from sims.models import Human, Family, Gender, Jobs
from flask_login import login_required

humans = Blueprint('humans', __name__)


@humans.route("/human/new", methods=['GET', 'POST'])
@login_required
def new_human():
    form = HumanForm()

    # Put all jobs from Job table to the form
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        try:
            # job = Job(form.job.data)
            gender = Gender(form.gender.data)
            job_id = int(form.job.data)
        except (KeyError, ValueError):
            flash('Invalid gender or job type', 'danger')
            return redirect(url_for('main.home'))

        human = Human(name=form.name.data, surname=form.surname.data,
                      gender=gender, age=form.age.data, job_id=job_id,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(human)
        db.session.commit()
        flash('Human has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('humans/create_human.html', title='New Human',
                           form=form, legend='New Human')


@humans.route("/human/<int:human_id>")
def human(human_id):
    human = Human.query.get_or_404(human_id)
    family = Family.query.get(human.family_id)
    job = Jobs.query.get(human.job_id)
    return render_template('humans/human.html', human=human, family=family, job=job)


@humans.route("/human/<int:human_id>/update", methods=['GET', 'POST'])
@login_required
def update_human(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]
    form.x_coordinate.data = human.x_coordinate
    form.y_coordinate.data = human.y_coordinate

    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
        except (KeyError, ValueError):
            flash('Invalid gender type', 'danger')
            return redirect(url_for('main.home'))

        human.name = form.name.data
        human.surname = form.surname.data
        human.gender = gender
        human.job_id = form.job.data
        human.age = form.age.data

        db.session.commit()
        flash('Your human has been updated!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.gender.default = human.gender.value
        form.process()

        form.name.data = human.name
        form.surname.data = human.surname
        form.age.data = human.age

    return render_template('humans/create_human.html', form=form, legend='Update Human',
                           title='Update Human', target='EDIT')


@humans.route("/human/<int:human_id>/delete", methods=['POST'])
@login_required
def delete_human(human_id):
    human = Human.query.get_or_404(human_id)

    db.session.delete(human)
    db.session.commit()
    flash('Human has been deleted!', 'success')
    return redirect(url_for('main.home'))


@humans.route("/human/<int:human_id>/leave_family", methods=['POST'])
@login_required
def human_leave_family(human_id):
    human = Human.query.get_or_404(human_id)
    human.family_id = None

    db.session.commit()
    flash(f'{human.name} left the family!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/humans/vehicle/<int:vehicle_id>", methods=['GET', 'POST'])
@login_required
def humans_vehicle(vehicle_id):
    humans = Human.query.all()
    return render_template('humans/humans_vehicle.html', title='List of Humans',
                           humans=humans, vehicle_id=vehicle_id)


@humans.route("/human/<int:human_id>/change_job", methods=['GET', 'POST'])
def change_job(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanJobForm()

    # Think of something smarter
    form.job.choices = [(job.id, job.name) for job in Jobs.query.all()]

    if form.validate_on_submit():
        human.job_id = form.job.data

        db.session.commit()
        flash('Job has been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        job = Jobs.query.get(human.job_id)
        if job:
            form.job.default = job.id
            form.process()

    return render_template('humans/change_job.html', form=form, legend='Change Job',
                           title='Change Job', human=human)


@humans.route("/human/<int:human_id>/leave_job", methods=['POST'])
def leave_job(human_id):
    human = Human.query.get_or_404(human_id)
    human.job_id = None

    db.session.commit()
    flash(f'{human.name} left the job!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@humans.route("/human/<int:human_id>/change_coordinates", methods=['GET', 'POST'])
def change_coordinates(human_id):
    human = Human.query.get_or_404(human_id)

    form = HumanCoordinatesForm()
    if form.validate_on_submit():
        human.x_coordinate = form.x_coordinate.data
        human.y_coordinate = form.y_coordinate.data

        flash('Coordinates have been changed!', 'success')
        return redirect(url_for('humans.human', human_id=human.id))
    elif request.method == 'GET':
        form.x_coordinate.data = human.x_coordinate
        form.y_coordinate.data = human.y_coordinate
    return render_template('humans/change_coordinates.html', form=form, legend='Change Coordinates',
                           title='Update Coordinates')

sims/vehicles/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.models import VehicleType, Color, Vehicle, Human
from flask_login import login_required

from sims.vehicles.forms import VehicleForm, VehicleColorForm

vehicles = Blueprint('vehicles', __name__)

ADULT_AGE = 18

@vehicles.route("/vehicle/new", methods=['GET', 'POST'])
@login_required
def new_vehicle():
    form = VehicleForm()
    if form.validate_on_submit():
        try:
            vehicle_type = VehicleType(form.type.data)
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid vehicle or color type', 'danger')
            return redirect(url_for('main.home'))
        vehicle = Vehicle(plate=form.plate.data, type=vehicle_type, color=color,
                          x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(vehicle)
        db.session.commit()
        flash('Vehicle has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('vehicles/create_vehicle.html', title='New vehicle',
                           form=form, legend='New Vehicle')


@vehicles.route("/vehicle/<int:vehicle_id>")
def vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    human = Human.query.get(vehicle.human_id)
    return render_template('vehicles/vehicle.html', vehicle=vehicle, human=human)


@vehicles.route("/vehicle/<int:vehicle_id>/update", methods=['GET', 'POST'])
@login_required
def update_vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    form = VehicleForm()
    if form.validate_on_submit():
        try:
            vehicle_type = VehicleType(form.type.data)
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid vehicle type', 'danger')
            return redirect(url_for('main.home'))
        vehicle.plate = form.plate.data
        vehicle.type = vehicle_type
        vehicle.color = color
        vehicle.x_coordinate = form.x_coordinate.data
        vehicle.y_coordinate = form.y_coordinate.data
        db.session.commit()
        flash('Your vehicle has been updated!', 'success')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))
    elif request.method == 'GET':
        form.type.default = vehicle.type.value
        form.color.default = vehicle.color.value
        form.process()

        form.plate.data = vehicle.plate
        form.x_coordinate.data = vehicle.x_coordinate
        form.y_coordinate.data = vehicle.y_coordinate
    return render_template('vehicles/create_vehicle.html', form=form, legend='Update Vehicle', title='Update Vehicle')


@vehicles.route("/vehicle/<int:vehicle_id>/delete", methods=['POST'])
@login_required
def delete_vehicle(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    db.session.delete(vehicle)
    db.session.commit()
    flash('Vehicle has been deleted!', 'success')
    return redirect(url_for('main.home'))


def is_adult(human):
    return not human.age < ADULT_AGE


@vehicles.route("/vehicle/<int:vehicle_id>/add_human/<int:human_id>", methods=['POST', 'GET'])
@login_required
def vehicle_add_human(vehicle_id, human_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    human = Human.query.get_or_404(human_id)

    if not is_adult(human):
        flash(f'{human.name} is not adult!', 'danger')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))

    vehicle.human_id = human.id
    db.session.commit()
    flash('Owner has been added!', 'success')
    return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))


@vehicles.route("/vehicle/<int:vehicle_id>/leave_human", methods=['POST'])
@login_required
def vehicle_delete_human(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)
    vehicle.human_id = None

    db.session.commit()
    flash('Human has been deleted!', 'success')
    return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))


@vehicles.route("/vehicle/<int:vehicle_id>/change_color", methods=['GET', 'POST'])
def change_color(vehicle_id):
    vehicle = Vehicle.query.get_or_404(vehicle_id)

    form = VehicleColorForm(color=2)
    if form.validate_on_submit():
        try:
            color = Color(form.color.data)
        except KeyError:
            flash('Invalid color type', 'danger')
            return redirect(url_for('main.home'))

        vehicle.color = color
        db.session.commit()
        flash('Color has been changed!', 'success')
        return redirect(url_for('vehicles.vehicle', vehicle_id=vehicle.id))
    elif request.method == 'GET':
        form.color.default = vehicle.color.value
        form.process()


    return render_template('vehicles/change_color.html', form=form, legend='Change Color', title='Update Color')

sims/templates/vehicles/change_color.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.color.label(class="form-control-label") }}
                    {% if form.color.errors %}
                        {{ form.color(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.color.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.color(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/vehicles/create_vehicle.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.plate.label(class="form-control-label") }}
                    {% if form.plate.errors %}
                        {{ form.plate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.plate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.plate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.type.label(class="form-control-label") }}
                    {% if form.type.errors %}
                        {{ form.type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.color.label(class="form-control-label") }}
                    {% if form.color.errors %}
                        {{ form.color(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.color.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.color(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.x_coordinate.label(class="form-control-label") }}
                    {% if form.x_coordinate.errors %}
                        {{ form.x_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.x_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.x_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.y_coordinate.label(class="form-control-label") }}
                    {% if form.y_coordinate.errors %}
                        {{ form.y_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.y_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.y_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/vehicles/vehicle.html
{% extends "layout.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-steel text-white">
                        <h2 class="text-white">Plate №: "{{ vehicle.plate }}"</h2>
                    </div>
                    <div class="card-body">
                        <p class="lead">🚗 Type: {{ vehicle.type.value }}</p>
                        <p class="lead">🌈 Color: {{ vehicle.color.value }}</p>
                        <p class="lead">📍 Coordinates: ({{ vehicle.x_coordinate }}, {{ vehicle.y_coordinate }})</p>
                        {% if human %}
                            <p class="lead">🚶‍♂️ Owner: {{ human.name }}</p>
                        {% else %}
                            <p class="lead">🚶‍♂️ Owner: No one</p>
                        {% endif %}

                        <div class="mt-3">
                            <a href="{{ url_for('vehicles.update_vehicle', vehicle_id=vehicle.id) }}" class="btn btn-primary">Edit</a>
                            <a href="{{ url_for('humans.humans_vehicle', vehicle_id=vehicle.id) }}"
                               class="btn btn-primary">Add owner</a>
                            <a href="{{ url_for('vehicles.change_color', vehicle_id=vehicle.id) }}"
                               class="btn btn-primary">Change Color</a>
                            <button class="btn btn-danger" id="deleteBtn" data-toggle="modal"
                                    data-target="#deleteModal">Delete
                            </button>
                            {% if human %}
                                <form class="mt-3"
                                      action="{{ url_for('vehicles.vehicle_delete_human', vehicle_id=vehicle.id) }}"
                                      method="POST">
                                    <input class="btn btn-primary" type="submit" value="Delete owner">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete vehicle?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('vehicles.delete_vehicle', vehicle_id=vehicle.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}