sims/pets/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, SelectField
from wtforms.validators import DataRequired, NumberRange, InputRequired

from sims.models import PetType, Gender


class PetForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    type = SelectField('Type', choices=[(pet_type.value, pet_type.value) for pet_type in PetType],
                       validators=[DataRequired()])
    gender = SelectField('Gender', choices=[(gender.value, gender.value) for gender in Gender],
                       validators=[DataRequired()])
    age = IntegerField('Age', validators=[InputRequired(), NumberRange(min=0, max=100)])
    x_coordinate = IntegerField('X coordinate', validators=[DataRequired(), NumberRange(min=-450, max=450)])
    y_coordinate = IntegerField('Y coordinate', validators=[DataRequired(), NumberRange(min=-200, max=200)])
    submit = SubmitField('Done')

sims/families/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.families.forms import FamilyForm
from sims.models import Human, Family, Pet, Jobs
from flask_login import login_required

families = Blueprint('families', __name__)


@families.route("/family/new", methods=['GET', 'POST'])
@login_required
def new_family():
    form = FamilyForm()

    if form.validate_on_submit():
        family = Family(name=form.name.data)

        db.session.add(family)
        db.session.commit()

        flash('Family has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('families/create_family.html', title='New Family',
                           form=form, legend='New Family')


def get_family_money(humans_in_family):
    print(humans_in_family)
    total = 0
    for human in humans_in_family:
        job = Jobs.query.get(human.job_id)
        total += job.salary
    return total

@families.route("/family/<int:family_id>")
def family(family_id):
    family = Family.query.get_or_404(family_id)
    humans_in_family = Human.query.filter_by(family_id=family.id).all()
    pets_in_family = Pet.query.filter_by(family_id=family.id).all()

    return render_template('families/family.html', family=family,
                           humans_in_family=humans_in_family,
                           pets_in_family=pets_in_family,
                           total_money=get_family_money(humans_in_family))


@families.route("/family/<int:family_id>/update", methods=['GET', 'POST'])
@login_required
def update_family(family_id):
    family = Family.query.get_or_404(family_id)

    form = FamilyForm()
    if form.validate_on_submit():
        family.name = form.name.data
        db.session.commit()
        flash('Your family has been updated!', 'success')
        return redirect(url_for('families.family', family_id=family.id))
    elif request.method == 'GET':
        form.name.data = family.name

    return render_template('families/create_family.html', form=form, legend='Update Family', title='Update Family')


@families.route("/family/<int:family_id>/delete", methods=['POST'])
@login_required
def delete_family(family_id):
    family = Family.query.get_or_404(family_id)

    Pet.query.filter_by(family_id=family.id).update({Pet.family_id: None})
    Human.query.filter_by(family_id=family.id).update({Human.family_id: None})

    db.session.delete(family)
    db.session.commit()
    flash('Family has been deleted!', 'success')
    return redirect(url_for('main.home'))


@families.route("/families")
@login_required
def all_families():
    families = Family.query.all()
    return render_template('families/families.html', title='List of Families',
                           families=families)


@families.route("/families/human/<int:human_id>", methods=['GET', 'POST'])
@login_required
def families_human(human_id):
    families = Family.query.all()
    return render_template('families/families_human.html', title='List of Families',
                           families=families, human_id=human_id)


@families.route("/families/pet/<int:pet_id>", methods=['GET', 'POST'])
@login_required
def families_pet(pet_id):
    families = Family.query.all()
    return render_template('families/families_pet.html', title='List of Families',
                           families=families, pet_id=pet_id)


@families.route("/families/house/<int:house_id>", methods=['GET', 'POST'])
@login_required
def families_house(house_id):
    families = Family.query.all()
    return render_template('families/families_house.html', title='List of Families',
                           families=families, house_id=house_id)


@families.route("/family/human_join/<int:family_id>/<int:human_id>", methods=['GET', 'POST'])
@login_required
def human_join_family(family_id, human_id):
    human = Human.query.get_or_404(human_id)
    family = Family.query.get_or_404(family_id)

    if human.surname != family.name:
        flash(f'{human.name} doesn\'t have {family.name} surname.', 'danger')
        return redirect(url_for('humans.human', human_id=human.id))

    human.family_id = family_id
    db.session.commit()

    flash(f'{human.name} has joined {family.name} family!', 'success')
    return redirect(url_for('humans.human', human_id=human.id))


@families.route("/family/pet_join/<int:family_id>/<int:pet_id>", methods=['GET', 'POST'])
@login_required
def pet_join_family(family_id, pet_id):
    pet = Pet.query.get_or_404(pet_id)
    family = Family.query.get_or_404(family_id)

    pet.family_id = family_id
    db.session.commit()

    flash(f'{pet.name} has joined {family.name} family!', 'success')
    return redirect(url_for('pets.pet', pet_id=pet.id))

sims/pets/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from sims import db
from sims.pets.forms import PetForm
from sims.models import Pet, Family, PetType, Plumbob, Gender
from flask_login import login_required

pets = Blueprint('pets', __name__)

@pets.route("/pet/new", methods=['GET', 'POST'])
@login_required
def new_pet():
    form = PetForm()
    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
            pet_type = PetType(form.type.data)
        except KeyError:
            flash('Invalid pet or gender type', 'danger')
            return redirect(url_for('main.home'))
        pet = Pet(name=form.name.data, type=pet_type, gender=gender, age=form.age.data,
                      x_coordinate=form.x_coordinate.data, y_coordinate=form.y_coordinate.data)
        db.session.add(pet)
        db.session.commit()
        flash('Pet has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('pets/create_pet.html', title='New Pet',
                           form=form, legend='New Pet')


@pets.route("/pet/<int:pet_id>")
def pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    family = Family.query.get(pet.family_id)
    return render_template('pets/pet.html', pet=pet, family=family)


@pets.route("/pet/<int:pet_id>/update", methods=['GET', 'POST'])
@login_required
def update_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)

    form = PetForm()
    if form.validate_on_submit():
        try:
            gender = Gender(form.gender.data)
            pet_type = PetType(form.type.data)
        except KeyError:
            flash('Invalid pet or gender type', 'danger')
            return redirect(url_for('main.home'))
        pet.name = form.name.data
        pet.type = pet_type
        pet.gender = gender
        pet.age = form.age.data
        pet.x_coordinate = form.x_coordinate.data
        pet.y_coordinate = form.y_coordinate.data
        db.session.commit()
        flash('Your pet has been updated!', 'success')
        return redirect(url_for('pets.pet', pet_id=pet.id))
    elif request.method == 'GET':
        form.gender.default = pet.gender.value
        form.type.default = pet.type.value
        form.process()

        form.name.data = pet.name
        form.age.data = pet.age
        form.x_coordinate.data = pet.x_coordinate
        form.y_coordinate.data = pet.y_coordinate
    return render_template('pets/create_pet.html', form=form, legend='Update Pet', title='Update Pet')


@pets.route("/pet/<int:pet_id>/delete", methods=['POST'])
@login_required
def delete_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)

    db.session.delete(pet)
    db.session.commit()
    flash('Pet has been deleted!', 'success')
    return redirect(url_for('main.home'))


@pets.route("/pet/<int:pet_id>/leave_family", methods=['POST'])
@login_required
def pet_leave_family(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    pet.family_id = None

    db.session.commit()
    flash(f'{pet.name} left the family!', 'success')
    return redirect(url_for('pets.pet', pet_id=pet.id))

sims/templates/pets/create_pet.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.type.label(class="form-control-label") }}
                    {% if form.type.errors %}
                        {{ form.type(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.type.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.type(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.gender.label(class="form-control-label") }}
                    {% if form.gender.errors %}
                        {{ form.gender(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.gender.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.gender(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.age.label(class="form-control-label") }}
                    {% if form.age.errors %}
                        {{ form.age(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.age.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.age(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.x_coordinate.label(class="form-control-label") }}
                    {% if form.x_coordinate.errors %}
                        {{ form.x_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.x_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.x_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.y_coordinate.label(class="form-control-label") }}
                    {% if form.y_coordinate.errors %}
                        {{ form.y_coordinate(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.y_coordinate.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.y_coordinate(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

sims/templates/pets/pet.html
{% extends "layout.html" %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header bg-steel text-white">
                        <h2 class="text-white">{{ pet.type.value }}: {{ pet.name }}</h2>
                    </div>
                    <div class="card-body">
                        <p class="lead">🐾 Type: {{ pet.type.value }}</p>
                        <p class="lead">🚻 Gender: {{ pet.gender.value }}</p>
                        <p class="lead">❔ Age: {{ pet.age }}</p>
                        <p class="lead">📍 Coordinates: ({{ pet.x_coordinate }}, {{ pet.y_coordinate }})</p>
                        {% if family %}
                            <p class="lead">👨‍👨‍👧‍👧 Family: {{ family.name }}</p>
                        {% else %}
                            <p class="lead">👨‍👨‍👧‍👧 Family: Not in the family</p>
                        {% endif %}
                        <p class="lead">🔹 Plumbob: {{ pet.plumbob.value }}</p>

                        <div class="mt-3">
                            <a href="{{ url_for('pets.update_pet', pet_id=pet.id) }}" class="btn btn-primary">Edit</a>
                            <a href="{{ url_for('families.families_pet', pet_id=pet.id) }}"
                               class="btn btn-primary">Join a Family</a>
                            <button class="btn btn-danger" id="deleteBtn" data-toggle="modal"
                                    data-target="#deleteModal">Delete
                            </button>
                            {% if family %}
                                <form class="mt-3" action="{{ url_for('pets.pet_leave_family', pet_id=pet.id) }}"
                                      method="POST">
                                    <input class="btn btn-danger" type="submit" value="Leave the Family">
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Pet?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('pets.delete_pet', pet_id=pet.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}